//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MijnMaaltijd.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecipeListLocales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecipeListLocales() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MijnMaaltijd.Locales.RecipeListLocales", typeof(RecipeListLocales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Dropbox {
            get {
                return ResourceManager.GetString("Dropbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GV aanpassing.
        /// </summary>
        public static string GlutenFreeAdaption {
            get {
                return ResourceManager.GetString("GlutenFreeAdaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis.
        /// </summary>
        public static string IsFish {
            get {
                return ResourceManager.GetString("IsFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GV.
        /// </summary>
        public static string IsGlutenFree {
            get {
                return ResourceManager.GetString("IsGlutenFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GV aanpasbaar.
        /// </summary>
        public static string IsGlutenFreeAdaptable {
            get {
                return ResourceManager.GetString("IsGlutenFreeAdaptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlees.
        /// </summary>
        public static string IsMeat {
            get {
                return ResourceManager.GetString("IsMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegan.
        /// </summary>
        public static string IsVegan {
            get {
                return ResourceManager.GetString("IsVegan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegan aanpasbaar.
        /// </summary>
        public static string IsVeganAdaptable {
            get {
                return ResourceManager.GetString("IsVeganAdaptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetarisch.
        /// </summary>
        public static string IsVegetarian {
            get {
                return ResourceManager.GetString("IsVegetarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicatie.
        /// </summary>
        public static string Publication {
            get {
                return ResourceManager.GetString("Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seizoen.
        /// </summary>
        public static string SeasonID {
            get {
                return ResourceManager.GetString("SeasonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeID {
            get {
                return ResourceManager.GetString("TypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegan aanpassing.
        /// </summary>
        public static string VeganAdaption {
            get {
                return ResourceManager.GetString("VeganAdaption", resourceCulture);
            }
        }
    }
}
