//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MijnMaaltijd.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MijnMaaltijdEntities : DbContext
    {
        public MijnMaaltijdEntities()
            : base("name=MijnMaaltijdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Recipe> Recipes { get; set; }
        public DbSet<Season> Seasons { get; set; }
        public DbSet<Type> Types { get; set; }
    }
}
