//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MijnMaaltijd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Publication { get; set; }
        public int SeasonID { get; set; }
        public int TypeID { get; set; }
        public bool IsMeat { get; set; }
        public bool IsFish { get; set; }
        public bool IsVegetarian { get; set; }
        public bool IsVegan { get; set; }
        public bool IsGlutenFree { get; set; }
        public bool IsVeganAdaptable { get; set; }
        public bool IsGlutenFreeAdaptable { get; set; }
        public string VeganAdaptation { get; set; }
        public string GlutenFreeAdaptation { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual Type Type { get; set; }
    }
}
